apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: duckdns-updater
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/xDeZex/universal
    targetRevision: main
    path: deploy/infra/duckdns-updater
  destination:
    server: https://kubernetes.default.svc
    namespace: duckdns-updater
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
