apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-redirect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/xDeZex/universal
    targetRevision: main
    path: deploy/infra-config/traefik-redirect
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
