apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: duckdns-token
  namespace: duckdns-updater
spec:
  encryptedData:
    token: AgA7IL3jm13shuZX4sbd1EKYOPFg1QArQXmTRCPxVKUUKXM5nNpl6aTZFf9Oa8qS7BCeeZ6N+tHZen1OEKUxex5S1lxM/1KLLNxIxWkuA3F+8F/5Jre7MUmONMdxLHtJ+kX8pyF3godiO7AiAFyY+t5awZWVC41UUb2o/9/r6x7ksmqJfQNqY5C3YYcT6tTzfEW6tHSeUywxiawY7WFVBagzVIqYJhngLhH3mH0hHgzJ1JmpkFqbxR1czAntiOw8oDEuH7cf4WdMJJ8lPDdG3xqrbtAIOqzyLXtmEz/48fdnzQKf99qHpqHV4N4oY9XOG4xIGEC9Aq8LHEmyuia+Rf8argLX26lf/fE1TS5+MgXSQ/doVCAYCFNUKqsgA7Lw4KYnA4MFB/vlyepg/IPyxSUDNmn17L22vHxd9mIxSGJi36dsAQWJucQztLMx9fAKrsyH+/xGUN4Z8cnU+53q1efEIIqbnNpRcO/MU+CLHn6tZa0zGhMg0losye37b3CWOrYR29gNT51aGVvPuhASBmGzjR8LgOrP250wGqRPL2eLcaLasa25OMiu4bHuKdUVOfzKTORtFF/SejTRrrVcMv2PYHl8qNra84/KsUbwrO04yLA1oZPSyjzWWddXR8U4CLapYeU5dvI9dn+3RRb6DAYFr+6QSv5XLGxeSU1EdRkBRnOeSnSvYVmOuJTibFs7r5SlMy+kasD9hwnbQb3hSPIVSmHWN3qQfIG0BlpF1xIu9bRK7CI=
  template:
    metadata:
      name: duckdns-token
      namespace: duckdns-updater
