apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- otel-config.yaml

images:
- name: ghcr.io/xdezex/universal/hello
  newName: ghcr.io/xdezex/universal/hello
  newTag: 3d065c5
