apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
        isDefault: false
        editable: false
